package com.example.hotelappref;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.example.hotelappref.database.AppDatabase;
import com.example.hotelappref.database.HotelDao;
import com.example.hotelappref.databinding.ActivityAddHotelBinding;
import com.example.hotelappref.models.Hotel;

/**
 * AddHotelActivity - Form screen for adding new hotels.
 *
 * KEY CONCEPTS:
 * - Form validation: Check required fields before saving
 * - ViewBinding: Access form fields type-safely
 * - Room Database: Persist hotel to database
 * - Activity results: Signal success/failure to calling activity
 *
 * WHY? This pattern is common in Android apps: a detail/form screen that
 * collects user input, validates it, and saves to persistent storage.
 */
public class AddHotelActivity extends AppCompatActivity {

    private ActivityAddHotelBinding binding;
    private HotelDao hotelDao;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityAddHotelBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        // Initialize database
        // WHY? We need to save the new hotel to persistent storage
        AppDatabase database = AppDatabase.getInstance(this);
        hotelDao = database.hotelDao();

        // Setup ActionBar with back button
        // WHY setDisplayHomeAsUpEnabled? Shows "<-" arrow to navigate back to parent activity
        if (getSupportActionBar() != null) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setTitle("Add New Hotel");
        }

        // Setup button listeners
        setupButtons();
    }

    private void setupButtons() {
        // Save button
        binding.btnSave.setOnClickListener(v -> saveHotel());

        // Cancel button
        binding.btnCancel.setOnClickListener(v -> {
            setResult(RESULT_CANCELED);
            finish();
        });
    }

    /**
     * Save the new hotel to the database.
     *
     * KEY STEPS:
     * 1. Get user input from EditText fields
     * 2. Validate required fields (name, phone, location)
     * 3. Set default values for optional fields
     * 4. Create Hotel object
     * 5. Insert into Room database
     * 6. Notify calling activity (MainActivity) of success
     *
     * WHY trim()? Removes leading/trailing whitespace from user input
     * WHY TextUtils.isEmpty()? Checks for both null and empty strings safely
     */
    private void saveHotel() {
        // Get input values
        // WHY .getText().toString().trim()? Converts Editable to String and removes whitespace
        String name = binding.editName.getText().toString().trim();
        String phone = binding.editPhone.getText().toString().trim();
        String website = binding.editWebsite.getText().toString().trim();
        String location = binding.editLocation.getText().toString().trim();
        String nearby = binding.editNearby.getText().toString().trim();
        String food = binding.editFood.getText().toString().trim();

        // Validate inputs - CRITICAL for exams!
        // WHY validate? Prevents saving incomplete/invalid data
        if (TextUtils.isEmpty(name)) {
            binding.editName.setError("Hotel name is required");
            binding.editName.requestFocus();
            return;  // Stop execution, don't save
        }

        if (TextUtils.isEmpty(phone)) {
            binding.editPhone.setError("Phone number is required");
            binding.editPhone.requestFocus();
            return;
        }

        if (TextUtils.isEmpty(location)) {
            binding.editLocation.setError("Location is required");
            binding.editLocation.requestFocus();
            return;
        }

        // Set default values for optional fields
        // WHY? Better user experience than storing empty strings
        if (TextUtils.isEmpty(website)) {
            website = "www.hotel.com";
        }
        if (TextUtils.isEmpty(nearby)) {
            nearby = "No nearby attractions listed";
        }
        if (TextUtils.isEmpty(food)) {
            food = "Restaurant available";
        }

        // Create Hotel object (id will be auto-generated by Room)
        Hotel newHotel = new Hotel(
                name,
                phone,
                website,
                location,
                nearby,
                food,
                R.mipmap.ic_launcher  // Using app's default launcher icon
        );

        // Save to database
        // WHY insert()? Room's DAO method adds the hotel to SQLite database
        // The @Insert annotation in HotelDao generated this method
        hotelDao.insert(newHotel);

        // Signal success to calling activity (MainActivity)
        // WHY setResult? Tells MainActivity the operation succeeded
        setResult(RESULT_OK);

        // Show success feedback to user
        // WHY Toast? Provides quick, non-intrusive feedback
        Toast.makeText(this, "Hotel added successfully!", Toast.LENGTH_SHORT).show();

        // Close this activity and return to MainActivity
        finish();
    }

    @Override
    public boolean onSupportNavigateUp() {
        onBackPressed();
        return true;
    }

    @Override
    public void onBackPressed() {
        setResult(RESULT_CANCELED);
        super.onBackPressed();
    }
}
